### ISSUE TITLE
视频文件增加mp4

### ISSUE THREAD

**Issue by zhujinwei0527123** [bililive-go/bililive-go#353]
### 新功能

能否将生成的视频文件增加mp4，并且做成可选项供不同需求的人群选择

**Comment by kira1928** [comment]
你是指让最后产出的录像变成mp4格式吗？
这个的话有一个配置选项是专门做这个的：
```yaml
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: false
```
在配置里向上面那样设置，就可以在录制结束后自动将 flv 文件转换成 mp4 文件。
如果`delete_flv_after_convert`也设为 true 的话，在转换成功后还会删除原始 flv 文件。
这是你需要的功能吗？
