### ISSUE TITLE
0.7.3转制mp4会出现失败的情况

### ISSUE THREAD

**Issue by sirlioniva** [bililive-go/bililive-go#366]
```yaml
rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: true
interval: 15
out_put_path: ./Downloads/live
feature:
  use_native_flv_parser: true
live_rooms:

out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 10m0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: false
timeout_in_us: 60000000
```

配置文件如上，开启flv parser后，录制pk会自动分段，挺好的，但是斗鱼直播间pk次数多了，会出现一次flv有容量，但是转制的mp4只有几百kb的情况，这几天出现了几次，我用第三方软件转制这个flv是可以正常转的，然后我仔细观察了一下文件生成时间，比flv最终生成的时间要早一点点

应该是mp4这个几百kb的文件会在本段flv录制结束前就出现，因为提前占用了这个文件名，导致没有继续转录mp4就停止了，本来如果flv和mp4都存着问题也不大，但第一天我是把删除flv也开着的，此时会只留下几百kb的mp4把几百m的flv删掉，第一天我发现视频不连贯，第二天都开启后发现了这个问题，本来pk的时候就会生成很多几十kb的重复文件，但这个问题我是这两天新发现的，所以建议不要开启删除flv，否则会漏掉一部分内容
