### ISSUE TITLE
录制的时长设置为1小时，无法生效

### ISSUE THREAD

**Issue by Andyziye2008** [bililive-go/bililive-go#559]
### 程序版本

V0.7.18

### 所使用的 config 文件的内容
```yaml
video_split_strategies:
  on_room_name_changed: true
  max_duration: 1h0m0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000
```

### 自由描述

录制的时长设置为1小时，无法生效，是不是我的代码有问题？
