### ISSUE TITLE
最新的文件大小分片功能，会导致少录一段内容

### ISSUE THREAD

**Issue by asdqwezxcczx** [bililive-go/bililive-go#565]
### 程序版本

0.7.18

### 所使用的 config 文件的内容
```yaml
rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 10
out_put_path:  ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.douyu.com/4913098
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 3500000000
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000
```
### 程序 log

time="2023-10-05 20:55:31" level=info msg="exit status 0xdfb9b0bb" host=

### 自由描述

视频达到最大的设置文件大小后，会显示“exit status 0xdfb9b0bb”，然后大概3min后才会重新开始录制，所以每次都会少录这部分的内容
