### ISSUE TITLE
B站哔哩哔哩主播场景切换改变分辨率导致之后内容花屏

### ISSUE THREAD

**Issue by faithererer** [bililive-go/bililive-go#837]
### 程序版本

docker最新

### 所使用的 config 文件的内容

```yaml
rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: true
  remove_symbol_other_character: true
live_rooms:
- url: https://live.bilibili.com/25035372
  is_listening: true
  quality: 0
  audio_only: false
- url: https://live.bilibili.com/279
  is_listening: true
  quality: 0
  audio_only: false
- url: https://live.bilibili.com/22746343
  is_listening: true
  quality: 0
  audio_only: false
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies:
  live.bilibili.com:  xxx
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000

```

### 程序 log

none

### 自由描述

这个加了没有用:
```yaml
feature:
  use_native_flv_parser: true
```
- 开播初始场景:

![Image](https://github.com/user-attachments/assets/60047a59-29e6-4ef8-90a8-8991642c7e7a)

- 切换主播场景后花屏

![Image](https://github.com/user-attachments/assets/f9f56a95-ee69-402b-a91b-a29710f37f58)
